### ISSUE TITLE
Holder: SS4 compatibility

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-omnipay#160]
This is a holder issue for upgrading to SilverStripe 4 compatibility.

## Pre-requisites

- [x] branch current master off for maintaining the current version 
- [x] update composer branch alias

## Tasks

- [x] update composer constraints for 3.x releases
- [x] namespace classes and implement core namespaces - include renaming folder structure for PSR-4 autoloading, and including an `.upgrade.yml` map for the upgrader tool
- [x] update configuration that requires namespacing
- [x] rename `code` to `src` (Separate from any PSR-2 changes so as to maintain git history)
- [x] update tests
- [x] PSR-2 compat if not already implemented (doesn't look too bad)
- [x] update Travis config to build PHP 7.x and minimum 5.5
- [x] update documentation as necessary
- [x] change module so that it gets installed into vendor folder
- [x] update translations and ensure translations are updated on transifex
- [x] define table names for datamodel classes

## Extra

- [x] ~~update Guzzle to latest version that still supports PHP 5.5 (guzzle/guzzle is abandoned)~~ _`~3.9` is required by `omnipay/common` - can't change_
- [ ] throw in any breaking changes that are waiting in the wings :-)
- [x] Integrate SS4 logging (via monolog)

**Comment by bummzack** [comment]
Sweet, thanks Robbie
